### PR TITLE
Added a new type of content - "form"

### PR DESCRIPTION
**Pull request by ummo93**
##### `content.yml`

```yaml
welcome:
  - text: Hello, world!
    typing: 250ms
    form:
      - <form.name> survey
      - <age> Your age
      - <phone> Your phone number
```

It's look's like a usually web form. After submitted, you can handle this event with botpress.hear method. For example:
```js
bp.hear({ type: 'form', formName: "survey" }, (event, next) => {
    // Your code
});
```
To know, what form has call the event, you can handle the form name with "formName" field, for this you may add to content.yml file "<form.name>" in the form section.

### CODE REVIEW

**Comment by slvnperron** [comment]
Is there a way to define:

- Type of form element? for example: Text, Boolean, Options
- Name / Description of the field
- Can the form be edited after it is submitted or does it become read-only?

Thanks

**Comment by ummo93** [comment]
@slvnperron to date, I have only implemented fields such as "input", so it's only "text" type. You're right, I should have described in more detail about receiving data from the form. 
If we have form like this: 
```yml
form:
      - <form.name> survey
      - <age> Your age
      - <phone> Your phone number
```
<age> - is a name of the input field in the form, and "Your age" is a placeholder of the input. So, if i want to receive user data from this field, i should do:
```js
bp.hear({ type: 'form', formName: "survey" }, (event, next) => {
    bp.logger.info(event.age); // 23, If user enter "23" in the input
});
```
//P.S form.name it's something like id for we have ability to "hear" it
Thank you!

**Comment by ummo93** [comment]
... the form was made so that after the submission only delivers the data to the backend, then how to deal with the data, we decide manually.

**Comment by slvnperron** [comment]
@ummo93 Thanks. I understand. But please let's make it in a way that you can decide how to display the fields in the UI, this is critical.

You have inspire yourself from what Slack released yesterday (esentially the same feature)https://api.slack.com/dialogs

**Comment by ummo93** [comment]
@slvnperron Thank you for link, it's should be awesome update! I will make it my next target.

**Comment by ummo93** [comment]
@slvnperron I updated my code. Now we can reply with form of next types: textarea, input, select, as the same as Slack web forms. Also, we can validating the form as the same as usually HTML web form. I have described an API of the forms in the README file.

**Pull request merged**
