### PR TITLE
Don't fetch conversation without id (resolve #34)

### LINKED ISSUE #34: Cannot get length of null when starting
I've noticed an issue in `fetchCurrentConversation` with the recent develop/x branch of botpress.
It's likely happening here `this.state.conversations.length` which is kinda expected that `conversations` can be `null`, but I haven't seen it before.

Guys, have you?

### PR DESCRIPTION
**Pull request by epaminond**

### CODE REVIEW

**Comment by emirotin** [comment]
Actually that's strange, as far as I can see we always call `fetchConversations` before we call `fetchCurrentConversation`.

One reason for the issue I can imaging is that `setState` is async and we actually don't wait for it to complete. You can achieve this by doing something like

```
return new Promise(resolve => this.setSate({ ... }, resolve))
```

**Comment by epaminond** [comment]
@emirotin , good catch. This helped indeed!

**Comment by emirotin** [comment]
It's a tricky part of React indeed, recently there was a detailed explanation why it behaves so: https://github.com/facebook/react/issues/11527#issuecomment-360199710

**Comment by slvnperron** [comment]
Great!

**Pull request merged**
